### ISSUE TITLE
Kserve model for image segmentation.

### ISSUE THREAD

**Issue by Ilovecode93** [lizzzcai/kserve-modelmesh-demo#1]
Hello. I've learnt a lot from this repo, but I'm still confused about my custom model.
Is it possible to inference a unet model trained by pytorch with Kserve??

**Comment by lizzzcai** [comment]
> Hello. I've learnt a lot from this repo, but I'm still confused about my custom model. Is it possible to inference a unet model trained by pytorch with Kserve??

Hi @Ilovecode93. Theoretically it should be able to support any custom models. Just make sure you have implement the `load` logic [here](https://github.com/lizzzcai/kserve-modelmesh-demo/blob/main/mlserver/models.py#L17-L19) and your predict logic [here](https://github.com/lizzzcai/kserve-modelmesh-demo/blob/main/mlserver/models.py#L29-L47). Tricky part in predict logic is you have to define your input and output format follow the kserve predict api.
I will suggest you follow this [tutorial](https://mlserver.readthedocs.io/en/latest/examples/custom/README.html) and test your unet model locally before moving it to modelmesh.

**Comment by Ilovecode93** [comment]
thanks，i will give it a shot.
